### ISSUE TITLE
save verify failed

### ISSUE THREAD

**Issue by jeffythedragonslayer** [hcs64/pif_rom_dumper#4]
Is there any more detail that can be displayed on why this failed?
![save_verify_failed](https://user-images.githubusercontent.com/13253146/144700341-ead5f4a7-80a7-4249-9fb2-57f810ffb89e.jpg)

**Comment by hcs64** [comment]
Hi, thanks for trying it out!

The error means that it wasn't able to read the saved data back from SRAM to verify it was saved correctly. This probably means your cartridge emulator / backup device isn't using an SRAM save type. Configuring the save type varies between devices, often based on a database of official games; there is an emerging standard to encode this in the header for homebrew, but pif_rom_dumper doesn't currently use it. Which device do you have?

**Comment by jeffythedragonslayer** [comment]
Not sure what you mean by a "cartridge emulator," you mean a "flashcart?"  I used the Everdrive 64 x7.

**Comment by hcs64** [comment]
Yeah I mean flashcart. For Everdrive I think you just need to add this line to the end of the `save_db.txt` file in the `ED64` directory:

```
0x5716C25D=3 (pif_rom_dumper)
```

Let me know if that works, if so I'll put up a readme explaining it.

**Comment by jeffythedragonslayer** [comment]
I put it at the end of the CRC detection section, as that looked like the right place.  It now prints "OK!" instead of "SAVE VERIFY FALIED" (though it returned to the ROM selection screen so quickly I had to select the pif_rom_dumper again to see that) but no dice finding the file:

```
D:\>where pifdata.bin /R .
INFO: Could not find files for the given pattern(s).
```

**Comment by hcs64** [comment]
It's saved in a normal SRAM save, you should find it in `ED64\Save`, I think it'll be called `pif_rom_dumper.sra`. You'll want to trim that down to just the first 0x7c0 (1984) bytes to isolate just the PIF ROM, the rest will be junk.

**Comment by jeffythedragonslayer** [comment]
oh ok; that filename contained what sounded like a verb not the noun "dump" so I didn't think that was it.
